### ISSUE TITLE
Where should I start?

### ISSUE THREAD

**Issue by bucaran** [michaelmacinnis/oh#13]
I like this project. Do you have any pointers or suggestions on how to get started with this? I've read [TTY Demystified](http://www.linusakesson.net/programming/tty/) a couple of times, but I am still lacking in tons of foundational concepts. Yet, I would like to contribute to this project.

Answering to any of the following questions would help:

1. Where to start reading your code?
2. Where should I focus first?
3. What are the tricky parts I should try to get out of the way first?

I've been dabbling with bash and fish for a while and I've come to love fish's orthogonality and terseness, while at the same time I've grown fond of bash crypticness. Oh, I want to try this one too.

**Comment by michaelmacinnis** [comment]
Thank you. I'm glad you like oh.

If you are interested in contributing code, one of the changes I've been
meaning to make is to modify oh to register a WordCompleter instead of the
current Completer function, complete (in task.go). The current complete
function is also very basic and I've been meaning to improve it's
suggestions.

Another way you could contribute would be to point out or correct areas
where the (currently very inomplete) manual is lacking or confusing. The
manual is generated from a set of scripts in the doctest/scripts directory.

If neither of these sound appealing you could always just start using oh
and see if there are things that you feel could be improved.

Let me know if you need further suggestions.
