### ISSUE TITLE
undefined: syscall.SYS_IOCTL (build fails on Solaris)

### ISSUE THREAD

**Issue by colstrom** [michaelmacinnis/oh#21]
```
$ go get -u -v github.com/michaelmacinnis/oh

github.com/michaelmacinnis/oh (download)
github.com/michaelmacinnis/adapted (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag main.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/peterh/liner (download)
github.com/michaelmacinnis/oh/pkg/system
# github.com/michaelmacinnis/oh/pkg/system

go/src/github.com/michaelmacinnis/oh/pkg/system/os_unix.go:49: undefined: syscall.SYS_IOCTL
go/src/github.com/michaelmacinnis/oh/pkg/system/os_unix.go:56: undefined: syscall.SYS_IOCTL
go/src/github.com/michaelmacinnis/oh/pkg/system/os_unix.go:83: undefined: syscall.Getpgrp
```

**Comment by mpmacin-cse** [comment]
Hmm. Sort of expected those to exist on Solaris. What version of Go are you using? And if you can dig a little deeper (not having a Solaris machine myself at the moment) does it look like we can use something equivalent on Solaris? Is there are syscall.Getpgid? I can probably make a constant to use instead of using syscall.SYS_IOCTL directly and set it so somethiiing appropriate on Solaris.

**Comment by michaelmacinnis** [comment]
Hmm. Sort of expected those to exist on Solaris. What version of Go are you using? And if you can dig a little deeper (not having a Solaris machine myself at the moment) does it look like we can use something equivalent on Solaris? Is there are syscall.Getpgid? I can probably make a constant to use instead of using syscall.SYS_IOCTL directly and set it so somethiiing appropriate on Solaris.

**Comment by colstrom** [comment]
Using `Go 1.7rc3` at the moment.

I'll see what I can dig up on the syscalls.

**Comment by colstrom** [comment]
Docs seem to include a `getpgid` call for Solaris, and the syscall` package for Go does include a `syscall.Getpgid` as well.

Sources
- https://docs.oracle.com/cd/E23824_01/html/821-1463/getpgid-2.html#scrolltoc
- https://golang.org/pkg/syscall/#Getpgid

**Comment by michaelmacinnis** [comment]
And right below Getpgid in the docs is Getpgrp. Looking at the source for 1.6.3 I can see Getpgid and Getpgrp defined for other OSs but not for Solaris. The only place I see either of these two functions for Solaris is in src/syscall/exec_solaris_test.go. I might be able to do something similar. It would be nice if the ioctl calls could be handled in the same way.

**Comment by colstrom** [comment]
Curious why support for those is missing in Go. 😕

**Comment by michaelmacinnis** [comment]
Try it now.

**Comment by michaelmacinnis** [comment]
Should build on Solaris now. (At least that is what gox tells me). Unfortunately, I don't think liner supports Solaris so command history, tab completion, etc. will be disabled.
