### ISSUE TITLE
Clarify POSIX / nonPOSIX compliance

### ISSUE THREAD

**Issue by mcandre** [michaelmacinnis/oh#25]
Thanks for uploading oh shell! Incidentally, is oh POSIX compliant? In other words, would `oh` work as a substitute for `/bin/sh`, or is oh really different?

**Comment by michaelmacinnis** [comment]
I'm confused by your question. A POSIX compliant shell is something quite specific. As I understand it, the POSIX shell specification was originally based on ksh-88 but I think the two have diverged since then.

There is a particularly good [answer](https://stackoverflow.com/a/16376043) on Stack Overflow to the question "Is there a minimally POSIX.2 compliant shell?"

[Your docker images](https://github.com/mcandre/docker-multi-sh) would be great for investigating some of the ambiguity in the POSIX shell spec with the shells that claim POSIX compliance (of which I think there are only a few) and those that have a switch or switches to enable more POSIX-like behavior.

To be explicit, oh isn't aiming for POSIX compliance. It aims to be familiar while improving the shell's programming language features.
