### ISSUE TITLE
String status type

### ISSUE THREAD

**Issue by michaelmacinnis** [michaelmacinnis/oh#34]
Oh has a status type to solve the zero exit status is true / non-zero exit status is false mismatch. On Plan 9, processes return a string status. Currently, oh's status type is a string type on Plan 9 and an integer type on other platforms. Instead of the status type behaving differently on different platforms, both the integer and string status types should be available on all platforms. Just need a name for the string status type...

**Comment by cryptorick** [comment]
(I'm pretending here that when you said "need a name" that it was a solicitation to the public for candidate names, although it was likely not what you meant and you were merely thinking out loud -- that's the risk of posting to the intertubes. :)

Some candidates:

- `stat`
- `statstring`
- `statusstring`
- `sstat`
- `sstatus`
- `strstat`
- `strstatus`
- `stringstat`
- `stringstatus`
- `returncode`
- `returnstatus`
- `statuscode`
- `*status`
- `status*`
- `status+`

Of them, my favorites are `statuscode` and `statusstring` because you would, by the name, more easily guess that they may have some kind of relation to `status`.

Anyway, this is also a chance to say that I believe this is a fantastic project.  Keep up the good work!

**Comment by michaelmacinnis** [comment]
Thank you! It was a solicitation to the public for candidate names in addition to thinking out loud. All good suggestions. I'd really like it if the name could be a single word, though. Maybe `status` as the name for the string status type and a new name for the integer status type. Something like statuscode, or returncode, or errorcode but, again, one word if possible.

**Comment by michaelmacinnis** [comment]
I think I'll go with errnum and errstr.

**Comment by cryptorick** [comment]
Sorry for being incommunicado for a while. I’m still interested in this project.

**Comment by michaelmacinnis** [comment]
No problem. Ditto.
