### ISSUE TITLE
Add docs for simple usability features

### ISSUE THREAD

**Issue by whereswaldon** [michaelmacinnis/oh#37]
I tried Oh, and it seems interesting. Certainly the programmability aspect is cool, and I like the idea of the type system. However, there's no documentation about how to customize anything (your prompt, for instance). I could read the source code, but I decided to try the shell on a whim at work, and I can't reasonably spend the time. I think it would be pretty easy to put together some guidance on how to perform basic operations like changing the prompt or the readline behavior, and it would make it easier for people like me to try things out comfortably.

If the above isn't supported yet, some docs indicating that would be just as good. ;P

It's a cool project though. I appreciate your hard work to improve the UNIX ecosystem!

**Comment by michaelmacinnis** [comment]
Thanks! I understand that your comment wasn't specifically about changing the prompt but I'll mention how to do that first:

    # Save the old prompt function.
    define oldprompt = $_sys_::prompt

    # Replace the existing prompt function.
    _sys_::export prompt: method (suffix) = {
        return 'myprompt> '
    }

This can be added to a .ohrc file in your home directory. The script pkg/boot/boot.oh, which is invoked when oh starts, looks for that file and sources it if it exists.

Customizing the readline behavior isn't possible and isn't currently a priority.

Part of the reason that changing the prompt isn't documented is because I'm not happy with how that's implemented. (I think a better way would be to have a background task that listens on a channel. Requests for the current prompt could be sent to that channel as well as a request to get or set the prompt function).

But the bigger reason is that documentation like that would give the illusion that oh is ready for general use. Take a look at some of @cryptorick's issues. If you can't see yourself expending a similar amount of effort then oh probably isn't for you yet.
